<?php

//dump::d($this);

?>
<style>
#coupon_content th,td {
	border: 1px solid #CCCCCC;
}

#coupon_content th {
	font-size: 12px;
	padding: 6px 0;
}

.coupon_price {
	font-size: 26px;
}

.input_button {
	background: -moz-linear-gradient(center top, #78BED8, #309FC4) repeat
		scroll 0 0 transparent;
	-webkit-box-shadow: rgba(0, 0, 0, 0.496094) 0 2px 4px;
	background-image: -webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8),
		to(#309FC4) );
	border: 1px solid #2D9DC2;
	border-radius: 9px 9px 9px 9px;
	box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
	color: #FFFFFF !important;
	cursor: pointer;
	display: inline-block;
	margin: 15px;
	padding: 4px 30px;
	text-align: center;
	text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
	vertical-align: middle;
}
</style>
<?=$this->form->Start('buy');?>
<?=$this->form->Input('coupon_id')?>
<div class="arc"
	style="border: 0px dotted red; background-color: white; margin: 5px; padding: 13px;">
<div class="hgroup1"
	style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
<h1 style="font-size: 20px;">クーポン購入</h1>
</div>
<h2
	style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 13px; font-size: 20px;">購入内容</h2>
<div id="coupon_content" style="padding-top: 8px;">
<table style="border-collapse: collapse;">
	<tr style="background-color: #DEEDCE;">
		<th style="border: 1px solid #CCCCCC; width: 50%; height: ">購入クーポン</th>
		<th>数量</th>
		<th>単価</th>
		<th>合計</th>
	</tr>
	<tr>
		<td>
			<img style="float: left; margin: 5px;" height="75px" src="../img/dummy.jpg">
			<p style="font-size: 13px;"><?=$record['coupon_description']?></p>
		</td>
		<td colspan="3" style="font-size: 40px; text-align: center;">
			<nobr>
				<span class="coupon_price">
					<span class="coupon_price">
						<?php $this->form->Input('quantity');?>
					</span>
					 × 
					<span id="coupon_normal_price" class="coupon_price">
						<?=$record['coupon_normal_price']?>
					</span>
					円 ＝ 
					<span id="price" class="coupon_price">
						<?=$record['coupon_normal_price']?>
					</span>
					円
				</span>
			</nobr>
			<p style="font-size: 13px; color: #FF9800;">▲数量の変更はこちらから</p>
		</td>
	</tr>
</table>
<div style="text-align: center"><?=$this->form->Input('submit_button')?>
</div>
</div>
</div>

<?=$this->form->Finish('buy')?>

<script>
function change_quantity(){
	var price = $('#coupon_normal_price').text();
	var quantity = $('#quantity').val();
		
	price = price * quantity;
	
	$('#price').text(price);
}

//	ドキュメントが読み込まれたら実行
$(document).ready(function(){
	var price = $('#price').text();
	var quantity = $('#quantity').val();
	
	if(0){
		$('#console').css('border','1px dotted blue');
		$('#console').css('margin','5px');
		$('#console').append('<h2>Console</h2><hr>');
		$('#console').append('<p>price='+price+'</p>');
		$('#console').append('<p>quantity='+quantity+'</p>');
	}
});

function log(str){
	$('#console').append('<p>'+str+'</p>');
}
</script>
<div id="console"></div>
