<?php
$select = array();
$select['table'] = 't_coupon';
$select['limit'] = 10;
$coupons = $this->mysql->select($select);
?>
<style>

#info_coupon_small{
	margin:3px;
	padding-bottom: 5px;
	background-color: #f0ffdd;
	border:1px solid gray;
	font-size: small;
	width: 234px;
}

div.info_coupon_small{
	padding: 3px;
	font-size: small;
	border:1px solid grey;
	border-width: 1px 0px 0px 0px;
}

p.info_coupon_small{
	font-size: small;
}

</style>
<div id="info_coupon_small" class="arc" >
	<div class="center" style="">
		<p class="small">おすすめのクーポン</p>
	</div>
	<?php foreach($coupons as $coupon): ?>
	<?php $this->Template('right_side_info_small.phtml',$coupon); ?>
	<?php endforeach; ?>
</div>
<?php
/*
$select = array();
$select['table'] = 't_coupon';
$select['limit'] = 10;
$coupons = $this->mysql->select($select);
*/
//  SELECTの定義を作成
$config = new Config();
$config->table = 't_coupon';
$config->limit = 10;
$config = $this->config()->select_coupon();
//  SELECTを実行
$coupons = $this->pdo()->select($config);
$this->d($coupons);
?>
<style>

#info_coupon_small{
	margin:3px;
	padding-bottom: 5px;
	background-color: #f0ffdd;
	border:1px solid gray;
	font-size: small;
	width: 234px;
}

div.info_coupon_small{
	padding: 3px;
	font-size: small;
	border:1px solid grey;
	border-width: 1px 0px 0px 0px;
}

p.info_coupon_small{
	font-size: small;
}

</style>
<div id="info_coupon_small" class="arc" >
	<div class="center" style="">
		<p class="small">おすすめのクーポン</p>
	</div>
	<?php foreach($coupons as $coupon): ?>
	<?php $this->Template('right_side_info_small.phtml',$coupon); ?>
	<?php endforeach; ?>
</div>

