<h1>仮登録の完了</h1>
<p>仮登録が完了しました。</p>
<?php
//  countdown
if( empty($countdown) ){
	$countdown = 5;
}
//  url
if( empty($url) ){
	$url = $this->ConvertURL('Ctrl:/');
}
$this->mark("URL: $url");
?>
<meta http-equiv="refresh" content="<?=$countdown?>;URL=<?=$url?>"/>
<div class="small">
    <div>
        About: <span id="countdown" class="red bigger bold"><?=$countdown?></span> min.
    </div>
</div>
<script>
function main(){
    //	looping 1sec.
    var timer_id = setInterval(function(){
        var countdown = $('#countdown').text();
        if( countdown > 0 ){
            countdown--;
            $('#countdown').text(countdown);
        }else{
            clearInterval(timer_id);
            document.location = '<?=$url?>';
        }
    }, 1000);
}
</script>