<?php
/* @var $this CouponApp */
?>
以下の内容でよろしいですか？
<?php $this->form()->Start($form_name,'./commit') ?>
<table>
	<tr>
		<td>
			名前
		</td>
		<td>
			<?php $this->form()->Value('first_name') ?>
			<?php $this->form()->Value('last_name') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('nick_name') ?>
		</td>
		<td>
			<?php $this->form()->Value('nick_name') ?><br/>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('email') ?>
		</td>
		<td>
			<?php $this->form()->Value('email') ?><br/>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('gender') ?>
		</td>
		<td>
			<?php $this->form()->Value('gender') ?><br/>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('birthday') ?>
		</td>
		<td>
			<?php $this->form()->Value('birthday') ?><br/>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('pref') ?>
		</td>
		<td>
			<?php $this->form()->Value('pref') ?><br/>
		</td>
	</tr>
	<tr>
		<td>
		
		</td>
		<td>
			<?php $this->form()->Input('submit'," この内容で登録する ") ?><br/>
		</td>
	</tr>
</table>
<?php $this->form()->Finish($form_name) ?>

<table>
	<tr>
		<td>
			<form action="./">
				<input type="submit" value=" 入力内容を修正する ">
			</form>
		</td>
	</tr>
</table>

