<?php $this->mark(); ?>
<style>
	#customer_informartion p{
		font-size: 14px;
	}
	#customer_informartion th, td {
		border: 1px solid #CCCCCC;
	}
	#customer_informartion table tr{
		height:2px;
	}
	
	#customer_informartion table tr th{
		background: none repeat scroll 0 0 #DEEDCE;
		font-size: 14px;
		width: 20px;
		padding: 8px 0;
		padding-left: 8px;
		width:100px;
	}
	
	#customer_informartion table tr td{
		/*width:400px;*/
		padding: 20px 0;
		font-size: 14px; 
		padding-left: 10px;
	}
	
	.input_button{
		background: -moz-linear-gradient(center top , #78BED8, #309FC4) repeat scroll 0 0 transparent;
		-webkit-box-shadow:rgba(0, 0, 0, 0.496094) 0 2px 4px;
		background-image:-webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8), to(#309FC4));
		border: 1px solid #2D9DC2;
		border-radius: 9px 9px 9px 9px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		margin: 15px;
		padding: 4px 30px;
		text-align: center;
		text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
		vertical-align: middle;
	}
</style>

<?=$this->form()->Start('form_customer');?>

<div class="arc" style="border: 0px dotted red; background-color:white; margin:5px; padding:13px;">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">登録情報</h1>
	</div>
	<div id="customer_informartion" style="padding-top:8px;">
		<table style="border-collapse: collapse;">
			<tr style="height:50px; padding: 25px 0;" align="left">
				<th style="width:5px;">名前</th>
				<td style="width:400px;">
					<span>
						姓：<?php $this->form()->Input('last_name');?>
						名：<?php $this->form()->Input('first_name');?>
						<p class="red"><?php $this->form()->InputError('last_name')?></p>
						<p class="red"><?php $this->form()->InputError('first_name')?></p>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>都道府県</th>
				<td><?php $this->form->Input('pref'); ?></td>
					<p class="red"><?php $this->form->InputError('pref');?></p>
			</tr>

			<tr align="left">
				<th>市区町村</th>
				<td>
					<span>
						<?php $this->form->Input('city'); ?>
						<p class="red"><?php $this->form->InputError('city');?></p>
						<p>例：新宿区</p>
					</span>
				</td>
			</tr>

			<tr align="left">
				<th>丁目番地</th>
				<td>
					<span>
						<?php $this->form->Input('address'); ?>
						<p class="red"><?php $this->form->InputError('address');?></p>
						<p>例：新宿1-1-1</p>
					</span>
				</td>
			</tr>

			<tr align="left">
				<th>建物名</th>
				<td>
					<span>
						<?php $this->form->Input('building'); ?>
						<p class="red"><?php $this->form->InputError('building');?></p>
						<p>例：新宿ビル5F</p>
					</span>
				</td>
			</tr>

			<tr align="left">
				<th>メールアドレス</th>
				<td><?php echo $mailaddr; ?><a href="/mypage/mailaddr_change">変更する</a></td>
			</tr>

			<tr align="left">
				<th>パスワード</th>
				<td><?php echo '******'; ?><a href="/mypage/password_change">変更する</a></td>
			</tr>

			<tr align="left">
				<th>myエリア</th>
				<td><?php $this->form->Input('myarea'); ?></td>
					<p class="red"><?php $this->form->InputError('myarea');?></p>
			</tr>

			<tr align="left">
				<th>生年月日</th>
				<td>
					<?php $this->form->Input('year'); ?>年
					<?php $this->form->Input('month'); ?>月
					<?php $this->form->Input('day'); ?>日
				</td>
					<p class="red"><?php $this->form->InputError('year');?></p>
					<p class="red"><?php $this->form->InputError('month');?></p>
					<p class="red"><?php $this->form->InputError('day');?></p>
			</tr>

			<tr align="left">
				<th>性別</th>
				<td><?php $this->form->Input('gender'); ?></td>
					<p class="red"><?php $this->form->InputError('gender');?></p>
			</tr>
		</table>
		<div style="text-align:center">
			<?=$this->form->Input('submit_button')?>
		</div>
	</div>
</div>
<p class="red"><?=$error?></p>

<?php $this->form()->Finish('form_customer'); ?>