<?php $this->mark(); ?>

<style>
	.mailaddr_change_mail p{
		margin-top:10px;
		font-size: 14px;
	}
	.input_button{
		background: -moz-linear-gradient(center top , #78BED8, #309FC4) repeat scroll 0 0 transparent;
		-webkit-box-shadow:rgba(0, 0, 0, 0.496094) 0 2px 4px;
		background-image:-webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8), to(#309FC4));
		border: 1px solid #2D9DC2;
		border-radius: 9px 9px 9px 9px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		margin: 15px;
		padding: 4px 30px;
		text-align: center;
		text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
		vertical-align: middle;
	}
</style>

<div class="arc" style="border: 0px dotted red; background-color:white; margin:5px; padding:13px;">
	<div style="margin-left:30px;">
		<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 10px;">
			<h1 style="font-size: 20px; ">メールアドレス変更</h1>
		</div>
		<div class ="mailaddr_change_mail">
			<p>メールを送信しました。</p>
			<p>メールに記載されているURLをクリックして登録を完了して下さい。</p>
		</div>
	</div>
</div>