<?php
/* @var $this CouponApp */
?>

<?php $this->form()->Start('form_coupon','commit') ?>

<div class="arc contents">
	<div class="title">
		<h1>登録情報 - 確認</h1>
	</div>
	<div class="contents2">
		<table class="table_border">
			<tr>
				<th>
					<?php $this->form()->Label('coupon_title') ?>
				</th	>
				<td>
					<?php $this->form()->Value('coupon_title') ?>
				</td>
			</tr>
			
			<tr>
				<th>
					<?php $this->form()->Label('coupon_description') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_description') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_normal_price') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_normal_price') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_price') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_price') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_num_top') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_num_top') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_num_bottom') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_num_bottom') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_start') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_start') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_finish') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_finish') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_expire') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_expire') ?>
				</td>
			</tr>
			<tr>
				<th>
					<nobr><?php $this->form()->Label('coupon_person_num') ?></nobr>
				</th>
				<td>
					<?php $this->form()->Value('coupon_person_num') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_image') ?>
				</th>
				<td>
					<?php if( $path = $this->form()->GetInputValue('coupon_image') ): ?>
						<img src="<?=$path?>"/>
					<?php endif; ?>
				</td>
			</tr>
		</table>
		<div class="div_submit">
			<?php $this->form()->Input('submit')?>
		</div>
	</div>
</div>

<?php $this->form()->Finish('form_coupon') ?>
