<?php
/* @var $this CouponApp */
?>

<?php $this->form()->Start('form_coupon','commit') ?>

<div class="arc contents">
	<div class="title">
		<h1>登録情報 - 確認</h1>
	</div>
	<div class="contents2">
		<table class="table_border">
			<tr>
				<th>
					<?php $this->form()->Label('coupon_title') ?>
				</th	>
				<td>
					<?php $this->form()->Value('coupon_title') ?>
				</td>
			</tr>
			
			<tr>
				<th>
					<?php $this->form()->Label('coupon_description') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_description') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_normal_price') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_normal_price') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_price') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_price') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_num_top') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_num_top') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_num_bottom') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_num_bottom') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_start') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_start') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_sales_finish') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_sales_finish') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->form()->Label('coupon_expire') ?>
				</th>
				<td>
					<?php $this->form()->Value('coupon_expire') ?>
				</td>
			</tr>
			<tr>
				<th>
					<nobr><?php $this->form()->Label('coupon_person_num') ?></nobr>
				</th>
				<td>
					<?php $this->form()->Value('coupon_person_num') ?>
				</td>
			</tr>
			
			<?php /* 元々のコード
			<tr>
				<th>
					<?php $this->form()->Label('coupon_image') ?>
				</th>
				<td>
					<?php if( $path = $this->form()->GetInputValue('coupon_image') ): ?>
						<img src="<?=$this->ConvertURL($path)?>"/>
					<?php endif; ?>
					<img src="<?php $this->form()->GetInputValue('coupon_image') ?>">
				</td>
			</tr>
			*/ ?>
			
			
			<tr>
				<th>
					クーポンのイメージ
				</th>
				<td>
					<img src="<?=$_POST['coupon_image_1'];?>"/>
				</td>
			</tr>
			

			
			<?php /*
			<?php $value = $this->form()->GetInputValueRawAll('form_coupon_image');?>
			<?php foreach ( $value as $key => $val ):?>
				<?php if( preg_match( '/coupon_image_??/', $key ) and $val !== null ):?>
					<?php $img_key = $key;?>
				<?php endif; ?>
			<?php endforeach; ?>
			<?php $this->form()->Clear('form_coupon_image');?>
			<?php $i = 1;?>
			<?php foreach ( $img_key as $k => $v ):?>
					<?php print '<tr>';?>
						<?php print '<th>';?>
							<?php //$this->form()->Label($img_key) ?>
							<?php print '<strong>クーポンのイメージ '.$i.'</strong>'; ?>
						<?php print '</th>';?>
						<?php print '<td>';?>
								<?php print '<img src="';?>
								<?=$this->ConvertURL($v)?>
								<?php print '"/>';?>
						<?php print '</td>';?>
					<?php print '</tr>';?>
				<?php $i++;?>
			<?php endforeach;?>
			*/ ?>
			
			
			
			
			</table>
		<div class="div_submit">
			<?php $this->form()->Input('submit')?>
		</div>
	</div>
</div>

<?php $this->form()->Finish('form_coupon') ?>
