
<script>
var selected = new Array();
var img_no   = parseInt(0);
var i        = parseInt(0);
var id       = null;
function show_input(img_no){
	img_no = img_no - 1;
	if( !selected[img_no] == true ){
		selected[img_no] = true;
		i = i + 1;
	}

	//console.log(selected.length);
	//console.log(selected);

	if( i >= 5 ){
		id = i + 1;
		String(id);
		//console.log(id);
		//console.log(i);
		if(document.getElementById(id).style.display == "none"){
			document.getElementById(id).style.display = "";
		}
	}
}

/*
function preview(ele, rownum){
    if (!ele.files.length){
         return;
    }
    var file = ele.files[0];
    if (!/^image\/(png|jpeg)$/.test(file.type)){
         return;
    }
    var img = document.createElement('img');
    img.width  = 100;
    img.height =  75; 
    var fr = new FileReader();
    fr.onload = function() {
        img.src = fr.result;
        var pv = "pv"+ rownum;
        String(pv);
        //document.getElementById(pv).appendChild(img);
        var oldpv = document.getElementById(pv);
        console.log(oldpv);//for test
        if( oldpv.getElementsByTagName('img').length > 0){
        	document.getElementById(pv).replaceChild(img, oldpv.firstChild);    
        } else {
            document.getElementById(pv).appendChild(img);//これ不要かも
		}
    }
    fr.readAsDataURL(file);
}
*/

</script>


<div class="contents">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">クーポン購入</h1>
	</div>
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 13px; font-size: 20px;">購入内容</h2>
	<div id="coupon_content" style="padding-top:8px;">
		
		<?php $this->form()->Start('form_coupon','confirm') ?>
		<table>
			<tr>
				<?php /* タイトル */ ?>
				<td>
					<?php $this->form()->Label('coupon_title') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_title') ?><br/>
					<?php $this->form()->Error('coupon_title') ?>
				</td>
			</tr>
			<tr>
				<?php /* 説明 */ ?>
				<td>
					<?php $this->form()->Label('coupon_description') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_description') ?><br/>
					<?php $this->form()->Error('coupon_description') ?>
				</td>
			</tr>
			<tr>
				<?php /* 通常価格 */ ?>
				<td>
					<?php $this->form()->Label('coupon_normal_price') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_normal_price') ?><br/>
					<?php $this->form()->Error('coupon_normal_price') ?>
				</td>
			</tr>
			<tr>
				<?php /* 販売価格 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_price') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_price') ?><br/>
					<?php $this->form()->Error('coupon_sales_price') ?>
				</td>
			</tr>
			<tr>
				<?php /* 最大販売数 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_num_top') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_num_top') ?><br/>
					<?php $this->form()->Error('coupon_sales_num_top') ?>
				</td>
			</tr>
			<tr>
				<?php /* 最小販売数 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_num_bottom') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_num_bottom') ?><br/>
					<?php $this->form()->Error('coupon_sales_num_bottom') ?>
				</td>
			</tr>
			<tr>
				<?php /* 販売開始日時 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_start') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_start') ?><br/>
					<?php $this->form()->Error('coupon_sales_start') ?>
				</td>
			</tr>
			<tr>
				<?php /* 終了開始日時 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_finish') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_finish') ?><br/>
					<?php $this->form()->Error('coupon_sales_finish') ?>
				</td>
			</tr>
			<tr>
				<?php /* 有効期限 */ ?>
				<td>
					<?php $this->form()->Label('coupon_expire') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_expire') ?><br/>
					<?php $this->form()->Error('coupon_expire') ?>
				</td>
			</tr>
			<tr>
				<?php /* 一人が購入できる枚数 */ ?>
				<td>
					<nobr><?php $this->form()->Label('coupon_person_num') ?></nobr>
				</td>
				<td>
					<?php $this->form()->Input('coupon_person_num') ?><br/>
					<?php $this->form()->Error('coupon_person_num') ?>
<input type="hidden" name="MAX_FILE_SIZE" value="2000000" >
					</td>
			</tr>
			
			<?php /*
			<tr>
				<td>
					<?php $this->form()->Label('coupon_image') ?>
				</td>
				<td>
					<?php if( $path = $this->form()->GetInputValue('coupon_image') ): ?>
						<img src="<?=$path?>"/>
					<?php endif; ?>
					<?php $this->form()->Input('coupon_image') ?><br/>
					<?php $this->form()->Error('coupon_image') ?>
				</td>
			</tr>
			*/ ?>
<?php //$this->form()->Label('MAX_FILE_SIZE') ?>
<?php //$this->form()->Input('MAX_FILE_SIZE') ?>

<?php $row = 1; ?>
<?php while( $row <= 10 ): ?>
<?php $img_key = "coupon_image_".$row;?>
<?php print '<tr id="';?>
<?=$row?>
<?php if( $row >= 6 ):?>
<?php print '" style="display:none;';?>
<?php endif; ?>
<?php print '">';?>
<?php print '<td>';?>
<?php $this->form()->Label($img_key) ?>
<?php print '</td>';?>
<?php print '<td id="pv';?>
<?php print $row;?>
<?php print '">';?>
<?php //print '<img src="/img/noimage.jpg">';?>
<?php //print '<br/>';?>
<?php if( $path = $this->form()->GetInputValue($img_key) ): ?>
<?php print '<img src="';?>
<?=$path?>
<?php print '"/>';?>
<?php endif; ?>
<?php $this->form()->Input($img_key) ?>
<?php print '<br/>';?>
<?php $this->form()->Error($img_key) ?>
<?php print '<br/>';?>
<?php print '</td>';?>
<?php print '</tr>';?>
<?php $row++;?>
<?php endwhile; ?>
			
			<tr>
				<td></td>
				<td>
				<br>
				画像は最低 5 枚選択が必要です。<br>
				(オプションで最大 10 枚まで選択できます。)
				</td>
			</tr>
			
			</table>
		<div style="text-align:center">
			<?php $this->form()->Input( 'submit', '　入力内容の確認　') ?>
		</div>
		<?php $this->form()->Finish('form_coupon') ?>
	</div>
</div>
