<script>
var img_id = parseInt(0);
function del_image(img_id){

	//	Reference:
	//		http://blog.joyfullife.jp/archives/2007/07/18115458.php
	//		http://nui.joyfullife.jp/sui/edit/
	//		http://itpro.nikkeibp.co.jp/article/COLUMN/20060607/240192/

	try {
		req = new ActiveXObject("Microsoft.XMLHTTP");
	} catch(e) {
		req = new XMLHttpRequest();
	}

	req.onreadystatechange = function()
	{
		var msg = document.getElementById("image_message");
		if (req.readyState == 4){
			if (req.status == 200){
					var data = req.responseText;
					var result = eval( '(' + data + ')' );
					var to_delete = String(result.deleted);
					var img_pv = document.getElementById(to_delete);
					img_pv.parentNode.removeChild(img_pv);
					msg.removeChild(msg.firstChild);
				
					var input_to_delete = to_delete+'_image';
					var del_target = document.getElementById(input_to_delete);
					del_target.parentNode.removeChild(del_target);
			} else {
				msg.innerHTML ="削除に失敗しました。";//メッセージの削除処理を追加する
			}
		} else {
			msg.innerHTML ="削除しています...";//メッセージ必要かどうか要確認
		}
	}

	req.open("post", "./del_image/", true);
	req.setRequestHeader("content-type", "application/x-www-form-urlencoded;");
	req.send(encodeURI('to_delete='+img_id));

}


function CheckImgCount(){
	var pv_div   = document.getElementById("uploaded_image");
	var pv_count = pv_div.getElementsByTagName("img");
	var len      = pv_count.length;
	var img_max = 10;// # of max image file(s)
	if( len >= img_max ){
		alert('画像は '+img_max+' 枚まで指定できます。');
		document.getElementById('form_coupon_image').reset();
		return false;
	}else{
		return true;
	}
}

function CheckImgCountMin(){
	var regexp   = new RegExp("^[a-zA-Z0-9]{32}_image$");

	form_to_send = document.getElementsByTagName('form')[0];
	
	var input_tags  = form_to_send.getElementsByTagName('input');

	var input_count = 0;
	for(var i =0;i<input_tags.length;i++){
		if(regexp.test(input_tags[i].getAttribute("id"))){
			input_count++;
		}
	}
	
	var img_min =  5;//	# of minimum image file(s)
	var img_max = 10;// # of max image file(s)
	if( input_count < img_min ){
		alert('画像を '+img_min+' 枚以上指定してください。');
		return false;
	}else if( input_count > img_max ){
		alert('画像は '+img_max+' 枚まで指定できます。');
		return false;
	}else{
		return true;
	}
}



function CheckAndSubmit(){
	var regexp   = new RegExp("^[a-zA-Z0-9]{32}_image$");

	form_to_send = document.getElementsByTagName('form')[0];
	
	var input_tags  = form_to_send.getElementsByTagName('input');

	var input_count = 0;
	for(var i =0;i<input_tags.length;i++){
		if(regexp.test(input_tags[i].getAttribute("id"))){
			input_count++;
		}
	}
	
	var img_min =  5;//	# of minimum image file(s)
	var img_max = 10;// # of max image file(s)
	if( input_count < img_min ){
		alert('画像を '+img_min+' 枚以上指定してください。');
		//return false;
		return;
	}else if( input_count > img_max ){
		alert('画像は '+img_max+' 枚まで指定できます。');
		//return false;
		return;
	}else{
		//return true;
		document.getElementsByTagName('form')[0].submit();
	}
}


</script>

<style>
/* Reference:
		http://www.halawata.net/2011/10/css-float-display-box/
		http://partisan.wwwxyz.jp/seed/2013/01/31/165435.php
*/

.uploaded_image {
	/* margin-left: 154px; */
	/* padding-left: 154px; */
}

.uploaded_image_div {
	display: inline-block;
	padding: 4px;
	margin-right: -4px;
}

html*.uploaded_image_div {
	display: inline;
	zoom: 1;
}


/*
html { font-size: 100%; }
.uploaded_image, .uploaded_image_div {
	margin: 0;
	padding: 0;
	list-style: none;
}

.uploaded_image {
	background: gray;
	letter-spacing: -1em;
	word-spacing: -1em;
}

:root div {
	font-size: 1px;
	letter-spacing: -1px;
	word-spacing: -1px;
}

.uploaded_image_div {
	display: inline-block;
	font-size: 1rem;
	letter-spacing: normal;
	word-spacing: normal;
	*display: inline;
	*zoom: 1;
}
*/

</style>

<div class="contents">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">クーポン購入</h1>
	</div>
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 13px; font-size: 20px;">購入内容</h2>
	<div id="coupon_content" style="padding-top:8px;">
		
		<?php $this->form()->Start('form_coupon','confirm') ?>
		<table>
			<tr>
				<?php /* タイトル */ ?>
				<td>
					<?php $this->form()->Label('coupon_title') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_title') ?><br/>
					<?php $this->form()->Error('coupon_title') ?>
				</td>
			</tr>
			<tr>
				<?php /* 説明 */ ?>
				<td>
					<?php $this->form()->Label('coupon_description') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_description') ?><br/>
					<?php $this->form()->Error('coupon_description') ?>
				</td>
			</tr>
			<tr>
				<?php /* 通常価格 */ ?>
				<td>
					<?php $this->form()->Label('coupon_normal_price') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_normal_price') ?><br/>
					<?php $this->form()->Error('coupon_normal_price') ?>
				</td>
			</tr>
			<tr>
				<?php /* 販売価格 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_price') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_price') ?><br/>
					<?php $this->form()->Error('coupon_sales_price') ?>
				</td>
			</tr>
			<tr>
				<?php /* 最大販売数 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_num_top') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_num_top') ?><br/>
					<?php $this->form()->Error('coupon_sales_num_top') ?>
				</td>
			</tr>
			<tr>
				<?php /* 最小販売数 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_num_bottom') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_num_bottom') ?><br/>
					<?php $this->form()->Error('coupon_sales_num_bottom') ?>
				</td>
			</tr>
			<tr>
				<?php /* 販売開始日時 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_start') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_start') ?><br/>
					<?php $this->form()->Error('coupon_sales_start') ?>
				</td>
			</tr>
			<tr>
				<?php /* 終了開始日時 */ ?>
				<td>
					<?php $this->form()->Label('coupon_sales_finish') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_sales_finish') ?><br/>
					<?php $this->form()->Error('coupon_sales_finish') ?>
				</td>
			</tr>
			<tr>
				<?php /* 有効期限 */ ?>
				<td>
					<?php $this->form()->Label('coupon_expire') ?>
				</td>
				<td>
					<?php $this->form()->Input('coupon_expire') ?><br/>
					<?php $this->form()->Error('coupon_expire') ?>
				</td>
			</tr>
			<tr>
				<?php /* 一人が購入できる枚数 */ ?>
				<td>
					<nobr><?php $this->form()->Label('coupon_person_num') ?></nobr>
				</td>
				<td>
					<?php $this->form()->Input('coupon_person_num') ?><br/>
					<?php $this->form()->Error('coupon_person_num') ?>
					</td>
			</tr>
			</table>
			
		<?php /*
		<div style="text-align:center">
			<?php $this->form()->Input( 'submit', '　入力内容の確認　') ?>
		</div>
		*/ ?>
		
		<?php /*
		<?php $this->d($data->array_img);?>
		<?php $array = null;?>
		<?php if($_POST):?>
			<?php $value = $_POST;?>
			<?php foreach( $value as $key => $val):?>
				<?php if( preg_match( '/^image_[a-zA-Z0-9]{32}$/', $key ) and $val !== null ):?>
				<?php $array[$key] = $val;?>
				<?php endif;?>
			<?php endforeach;?>
			
<?php if($array):?>
		*/ ?>

<?php if($data->array_img):?>
<?php $array = $data->array_img;?>

<?php foreach( $array as $k => $v ):?>
<?php //$k2 = str_replace("image_", "", $k);?>
<?php print '<input id="'.$k.'_image" type="hidden" name="image_'.$k.'" value="'.$v.'">';?>
<?php endforeach;?>
<?php endif;?>		
			
		<?php //endif;?>

		<?php $this->form()->Finish('form_coupon') ?>

		<!-- <div style="width:100%;height:150px;margin-top:-150px;"> -->

		<table>
			<tr>
				<td style="width: 154px;">
					クーポンのイメージ
				</td>
				<td>
		
		
		<!-- <div> -->
		<form name="form_coupon_image" enctype="multipart/form-data" method="post" action="./upload/" target="targetFrame" id="form_coupon_image">
			<input type="hidden" name="MAX_FILE_SIZE" value="2000000" >
			<input type="file" name="upload_image" required><br>
			<input type="submit" value="画像をアップロード" onClick="return CheckImgCount();">
			<span id="image_message"></span><!-- エラーメッセージ表示用 -->
		</form>
		<!-- </div> -->

				</td>
			</tr>
		</table>


		<div id="uploaded_image" >
<?php if($array):?>
	<?php foreach( $array as $k => $v ):?>
	<?php //$k = str_replace("image_", "", $k);?>
	<?php //$v = $this->ConvertUrl("app:$v");//この処理不要かも?>
<?php print '<div class="uploaded_image_div" id="'.$k.'">';?>
<?php print '<div><img src="'.$v.'" width="100" height="75"></div>';?>
<?php print '<div><span class="image_del_button">';?>
<?php print "<a href=\"javascript: del_image('$k')\">[x]</a>";?>
<?php print '</span></div></div>';?>
	<?php endforeach;?>
<?php endif;?>		
		</div>
		
		<div id="result">
		<iframe id="targetFrame" src="" style="width:0px;height:0px;border:0px;"></iframe>
		<!-- 以下はテスト用のiframe -->
		<!-- <iframe id="targetFrame" src="" style="width:400px;height:200px;"></iframe> -->
		</div>
		
		<div style="text-align:center">
		<input type="button" name="submit" value="登録する" class="submit" onclick="javascript: CheckAndSubmit();">
		</div>
		
	</div>
</div>
