<style>
	#coupon_content th, td {
		border: 1px solid #CCCCCC;
	}
	#coupon_content th {
		font-size: 12px;
		padding: 6px 0;
	}
	.coupon_price{
		font-size: 26px;
	}
	.input_button{
		background: -moz-linear-gradient(center top , #78BED8, #309FC4) repeat scroll 0 0 transparent;
		-webkit-box-shadow:rgba(0, 0, 0, 0.496094) 0 2px 4px;
		background-image:-webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8), to(#309FC4));
		border: 1px solid #2D9DC2;
		border-radius: 9px 9px 9px 9px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		margin: 15px;
		padding: 4px 30px;
		text-align: center;
		text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
		vertical-align: middle;
	}
</style>


<div class="arc" style="border: 0px dotted red; background-color:white; margin:5px; padding:13px;">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">マイクーポン</h1>
	</div>
	<div id="coupon_content" style="padding-top:8px;">
		<?php
			if(empty($coupons)){
				echo 'クーポンがありません。';
			}else{
		?>
		<table style="border-collapse: collapse; width:100%;">
			<tr style="background-color: #DEEDCE;">
				<th style="border: 1px solid #CCCCCC; width:60%;">クーポン内容</th>
				<th>購入枚数</th>
				<th>有効期限</th>
			</tr>
			<?php
				foreach($coupons as $coupon):
			?>
				<tr>
					<td>
						<p style="font-weight: bold; font-size:13px;"><?php echo $coupon['coupon_title']; ?></p>
						<a href="/buy/<?=$coupon['coupon_id']?>" style="color: #0891BE; font-size:13px;">
							<?php echo $coupon['coupon_description']; ?>
						</a>
					</td>
					<td style="font-size:13px; text-align: center; vertical-align: middle;">
						<?php echo $coupon['num']; ?>
					</td>
					<td style="font-size:13px; text-align: center; vertical-align: middle;">
						<?php echo $coupon['coupon_expire']; ?>
					</td>
				</tr>
			<?php
				endforeach;
			?>
		</table>
		<?php
			}
		?>
	</div>
</div>


<?php
/*

<?php $this->mark(); ?>

<h3>クーポン一覧</h3>

<?php
//	$this->d($t_coupons);
?>
<table>
	<tr>
		<th>タイトル</th>
		<th>説明</th>
		<th>価格</th>
	</tr>
<?php foreach($t_coupons as $t_coupon): ?>
	<tr>
		<td><?php echo $t_coupon['coupon_title']; ?></td>
		<td><?php echo $t_coupon['coupon_description']; ?></td>
		<td><?php echo $t_coupon['coupon_normal_price']; ?></td>
	</tr>
<?php endforeach; ?>
</table>

*/

?>