<?php
/* @var $this CouponApp */
?>
<?php $this->form()->Start( $data->form_name, 'confirm' ) ?>
	<?php $this->form()->Label('email') ?>
	<?php $this->form()->Input('email') ?>
	<?php $this->form()->Error('email') ?>
	<br>
	<?php $this->form()->Label('email_confirm') ?>
	<?php $this->form()->Input('email_confirm') ?>
	<?php $this->form()->Error('email_confirm') ?>
	<br>
	<?php $this->form()->Input('submit','　確認　') ?>
<?php $this->form()->Finish($data->form_name) ?>