<?php
/* @var $this CouponApp */
$coupon_id = $this->GetCouponID();
$record = $this->pdo()->quick(" t_coupon.coupon_id = $coupon_id ");
$register_flag = false; // TODO
?>

<div class="arc" style="background-color:white; margin:5px; padding:13px;">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">クーポン購入</h1>
	</div>

	<?php if($register_flag): ?>
	<div class ="register_message" style="text-align:center; padding-top:10px;">
		<p><strong style="font-size:22px;">会員登録が完了しました。</strong></p>
		<p style="font-size:14px;">これよりクーポンをご購入いただけます。</p>
	</div>
	<?php endif; ?>
	
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 20px; font-size: 20px;">購入内容</h2>
	
<?=$this->form()->Start('form_buy');?>
	<div id="coupon_content" style="padding-top:8px;">
		<table style="border-collapse: collapse; width:100%;">
			<tr style="background-color: #DEEDCE;">
				<th style="border: 1px solid #CCCCCC; width:50%; height:">購入クーポン</th>
				<th>数量</th>
				<th>単価</th>
				<th>合計</th>
			</tr>
			<tr>
				<td>
					<img style="float:left; margin: 5px;" height="75px" src="../img/dummy.jpg">
					<p style="font-size:13px;"><?=$record['coupon_description']?></p>
				</td>
				<td colspan="3" style="font-size: 40px; text-align:center;">
					<nobr>
						<span class="coupon_price">
							<span class="coupon_price">
							<?php $this->form()->Input('quantity');?>
							</span>
							×
							<span id="coupon_normal_price" class="coupon_price"><?=$record['coupon_normal_price']?></span>円
							＝
							<span id="price" class="coupon_price"><?=$record['coupon_normal_price']?></span>円
						</span>
					</nobr>
					<p style="font-size:13px; color: #FF9800;">▲数量の変更はこちらから</p>
				</td>
			</tr>
		</table>
		<div style="text-align:center">
			<?php $this->form()->Input('submit',' 数量を変更 ') ?>
		</div>
	</div>
<?=$this->form()->Finish('form_buy');?>
	
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 40px; font-size: 20px;">お客様情報</h2>

	<div id="customer_informartion" style="padding-top:8px;">
		<p style="padding: 0 0 8px;">▼以下にてお支払いに関する情報をご記入ください。</p>	
		
		<?=$this->form()->Start('form_address',"app:/buy/$coupon_id/reconfirm");?>		
		<table style="border-collapse: collapse;">
			<tr style="height:50px; padding: 25px 0;" align="left">
				<th>お名前</th>
				<td>
					<span>
						姓：<?php $this->form()->Input('last_name') ?>
						名：<?php $this->form()->Input('first_name') ?>
						<?php $this->form()->Error('last_name') ?>
						<?php $this->form()->Error('first_name') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>郵便番号</th>
				<td>
					<span>
						<?php $this->form()->Input('zipcode') ?>
						<?php $this->form()->Error('zipcode') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>都道府県</th>
				<td>
					<span>
						<?php $this->form()->Input('pref') ?>
						<?php $this->form()->Error('pref') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>市区町村</th>
				<td>
					<p>例：新宿区</p>
					<?php $this->form()->Input('city') ?>
					<?php $this->form()->Error('city') ?>
				</td>
			</tr>
			<tr align="left">
				<th>丁目番地</th>
				<td>
					<p>例：新宿1-1-1</p>
					<?php $this->form()->Input('address') ?>
					<?php $this->form()->Error('address') ?>
				</td>
			</tr>
			<tr align="left">
				<th>建物名</th>
				<td>
					<p>例：新宿ビル5F</p>
					<?php $this->form()->Input('building') ?>
					<?php $this->form()->Error('building') ?>
				</td>
			</tr>
		</table>
		<div style="text-align:center">
			<?php $this->form()->Input('submit',' 入力内容を確認する ') ?>
		</div>
		<?php $this->form()->Finish('form_address') ?>
	</div>
</div>

<script>
function change_quantity(){
	var price = $('#coupon_normal_price').text();
	var quantity = $('#quantity').val();
		
	price = price * quantity;
	
	$('#price').text(price);
}

//	ドキュメントが読み込まれたら実行
$(document).ready(function(){
	var price = $('#price').text();
	var quantity = $('#quantity').val();
	
	if(0){
		$('#console').css('border','1px dotted blue');
		$('#console').css('margin','5px');
		$('#console').append('<h2>Console</h2><hr>');
		$('#console').append('<p>price='+price+'</p>');
		$('#console').append('<p>quantity='+quantity+'</p>');
	}
});

function log(str){
	$('#console').append('<p>'+str+'</p>');
}
</script>
<div id="console"></div>

