<?php
/* @var $this CouponApp */
$coupon_id = $this->GetCouponID();
$record = $this->pdo()->quick(" t_coupon.coupon_id = $coupon_id ");
?>
<style>
	#coupon_content th, td {
		border: 1px solid #CCCCCC;
	}
	#coupon_content th {
		font-size: 12px;
		padding: 6px 0;
	}
	#customer_informartion p{
		font-size: 14px;
	}
	#customer_informartion th, td {
		border: 1px solid #CCCCCC;
	}
	#customer_informartion table tr{
		height:2px;
	}
	#customer_informartion table tr th{
		background: none repeat scroll 0 0 #DEEDCE;
		font-size: 14px;
		width: 20px;
		padding: 8px 0;
		padding-left: 8px;
		width:100px;
	}
	#customer_informartion table tr td{
		width:400px;
		padding: 20px 0;
		font-size: 14px; 
		padding-left: 10px;
	}
	.coupon_price{
		font-size: 26px;
	}
	
	.input_button{
		background: -moz-linear-gradient(center top , #78BED8, #309FC4) repeat scroll 0 0 transparent;
		-webkit-box-shadow:rgba(0, 0, 0, 0.496094) 0 2px 4px;
		background-image:-webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8), to(#309FC4));
		border: 1px solid #2D9DC2;
		border-radius: 9px 9px 9px 9px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		margin: 15px;
		padding: 4px 30px;
		text-align: center;
		text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
		vertical-align: middle;
	}
	.register_message p{
		margin-top:10px;
		font-size: 14px;
	}
</style>

<?=$this->form()->Start('form_buy_confirm');?>
<div class="arc" style="background-color:white; margin:5px; padding:13px;">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">クーポン購入</h1>
	</div>

	<?php if($register_flag): ?>
	<div class ="register_message" style="text-align:center; padding-top:10px;">
		<p><strong style="font-size:22px;">会員登録が完了しました。</strong></p>
		<p style="font-size:14px;">これよりクーポンをご購入いただけます。</p>
	</div>
	<?php endif; ?>
	
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 20px; font-size: 20px;">購入内容</h2>
	
	<div id="coupon_content" style="padding-top:8px;">
		<table style="border-collapse: collapse; width:100%;">
			<tr style="background-color: #DEEDCE;">
				<th style="border: 1px solid #CCCCCC; width:50%; height:">購入クーポン</th>
				<th>数量</th>
				<th>単価</th>
				<th>合計</th>
			</tr>
			<tr>
				<td>
					<img style="float:left; margin: 5px;" height="75px" src="../img/dummy.jpg">
					<p style="font-size:13px;"><?=$record['coupon_description']?></p>
				</td>
				<td colspan="3" style="font-size: 40px; text-align:center;">
					<nobr>
						<span class="coupon_price">
							<span class="coupon_price">
							<?php $this->form()->Input('quantity');?>
							</span>
							×
							<span id="coupon_normal_price" class="coupon_price"><?=$record['coupon_normal_price']?></span>円
							＝
							<span id="price" class="coupon_price"><?=$record['coupon_normal_price']?></span>円
						</span>
						<p style="font-size:13px; color: #FF9800;">▲数量の変更はこちらから</p>
					</nobr>
				</td>
			</tr>
		</table>
	</div>
	
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 40px; font-size: 20px;">お客様情報</h2>
	<div id="customer_informartion" style="padding-top:8px;">
		<p style="padding: 0 0 8px;">▼以下にてお支払いに関する情報をご記入ください。</p>
		<table style="border-collapse: collapse;">
			<tr style="height:50px; padding: 25px 0;" align="left">
				<th>お名前</th>
				<td>
					<span>
						姓：<?php $this->form()->Input('last_name') ?>
						名：<?php $this->form()->Input('first_name') ?>
						<?php $this->form()->Error('last_name') ?>
						<?php $this->form()->Error('first_name') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>郵便番号</th>
				<td>
					<span>
						<?php $this->form()->Input('postcode') ?>
						<?php $this->form()->Error('postcode') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>都道府県</th>
				<td>
					<span>
						<?php $this->form()->Input('pref') ?>
						<?php $this->form()->Error('pref') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>市区町村</th>
				<td>
					<span>
						<p>例：新宿区</p>
						<?php $this->form()->Input('city') ?>
						<?php $this->form()->Error('city') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>丁目番地</th>
				<td>
					<span>
						<p>例：新宿1-1-1</p>
						<?php $this->form()->Input('address') ?>
						<?php $this->form()->Error('address') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>建物名</th>
				<td>
					<span>
						<p>例：新宿ビル5F</p>
						<?php $this->form()->Input('building') ?>
						<?php $this->form()->Error('building') ?>
					</span>
				</td>
			</tr>
		</table>
		<div style="text-align:center">
			<?php $this->form()->Input('submit') ?>
		</div>
	</div>
</div>

<?php $this->form()->Finish('form_buy_confirm') ?>

<script>
function change_quantity(){
	var price = $('#coupon_normal_price').text();
	var quantity = $('#quantity').val();
		
	price = price * quantity;
	
	$('#price').text(price);
}

//	ドキュメントが読み込まれたら実行
$(document).ready(function(){
	var price = $('#price').text();
	var quantity = $('#quantity').val();
	
	if(0){
		$('#console').css('border','1px dotted blue');
		$('#console').css('margin','5px');
		$('#console').append('<h2>Console</h2><hr>');
		$('#console').append('<p>price='+price+'</p>');
		$('#console').append('<p>quantity='+quantity+'</p>');
	}
});

function log(str){
	$('#console').append('<p>'+str+'</p>');
}
</script>
<div id="console"></div>

