<?php
/* @var $this CouponApp */
$coupon_id = $data->coupon_id;
$t_coupon  = $data->t_coupon;
?>

<div class="arc" style="background-color:white; margin:5px; padding:13px;">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">クーポン購入</h1>
	</div>
	
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 20px; font-size: 20px;">購入内容</h2>
	
	<?php
	$data->form_name = $data->form_name_buy;
	$this->template('form_buy_confirm.phtml',$data);
	?>
	
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 40px; font-size: 20px;">お客様情報</h2>
		
	<?php
	$data->form_name    = $data->form_name_address; 
	$data->submit_label = ' この内容で購入 ';
	$this->template('form_address_confirm.phtml',$data);
	?>
	
	<!-- 戻るボタン -->
	<form action="<?=$this->ConvertURL("app:/buy/$coupon_id/address")?>" method="post">
		<div style="text-align:center">
			<input type="submit" class="submit" value=" 入力内容を修正する ">
		</div>
	</form>
</div>
