<?php
/* @var $this CouponApp */
?>
		<?=$this->form()->Start( $data->form_name, $data->form_action );?>
		<table style="border-collapse: collapse;">
			<tr style="height:50px; padding: 25px 0;" align="left">
				<th>お名前</th>
				<td>
					<span>
						姓：<?php $this->form()->Input('last_name') ?>
						名：<?php $this->form()->Input('first_name') ?>
						<?php $this->form()->Error('last_name') ?>
						<?php $this->form()->Error('first_name') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>郵便番号</th>
				<td>
					<span>
						<?php $this->form()->Input('zipcode') ?>
						<?php $this->form()->Error('zipcode') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>都道府県</th>
				<td>
					<span>
						<?php $this->form()->Input('pref') ?>
						<?php $this->form()->Error('pref') ?>
					</span>
				</td>
			</tr>
			<tr align="left">
				<th>市区町村</th>
				<td>
					<p>例：新宿区</p>
					<?php $this->form()->Input('city') ?>
					<?php $this->form()->Error('city') ?>
				</td>
			</tr>
			<tr align="left">
				<th>丁目番地</th>
				<td>
					<p>例：新宿1-1-1</p>
					<?php $this->form()->Input('address') ?>
					<?php $this->form()->Error('address') ?>
				</td>
			</tr>
			<tr align="left">
				<th>建物名</th>
				<td>
					<p>例：新宿ビル5F</p>
					<?php $this->form()->Input('building') ?>
					<?php $this->form()->Error('building') ?>
				</td>
			</tr>
		</table>
		<div style="text-align:center">
			<?php $this->form()->Input( 'submit', $data->submit_label ) ?>
		</div>
		<?php $this->form()->Finish($data->form_name) ?>
		