<?php
/* @var $this CouponApp */
$t_coupon = $data->t_coupon;
$quantity = $this->form()->GetValue('quantity',$data->form_name);
$quantity = ctype_digit($quantity) ? $quantity: 1;
$coupon_price_normal = $t_coupon['coupon_normal_price'];
$coupon_price_sales  = $t_coupon['coupon_sales_price'];
$coupon_price_total  = $quantity * $coupon_price_sales;
$coupon_description  = $t_coupon['coupon_description'];
?>

<style>
table{
	border-width: 0px;
}
tr{
	border-width: 0px;
}
th{
	border-width: 0px;
}
td{
	border-width: 0px;
}
</style>
<?php $this->form()->Start( $data->form_name, $data->form_action ); ?>
<table style="border-collapse: collapse; width:100%;">
	<tr style="background-color: #DEEDCE;">
		<th style="border-width: 1px 0px; border-left-width:1px;">購入クーポン</th>
		<th style="border-width: 1px 0px;">数量</th>
		<th style="border-width: 1px 0px;"> </th>
		<th style="border-width: 1px 0px;"> </th>
		<th style="border-width: 1px 0px;">単価</th>
		<th style="border-width: 1px 0px;"> </th>
		<th style="border-width: 1px 0px;"> </th>
		<th style="border-width: 1px 0px; border-right-width:1px;">合計</th>
	</tr>
	<tr>
		<td class="small" rowspan="2" style="width:50%;">
			<img class="img_coupon float_left" src="../img/dummy.jpg">
			<p><?=nl2br($this->wiki2($coupon_description))?></p>
		</td>
		<td class="center" style="height: 3em;">
			<span class="coupon_price"><?php $this->form()->Input('quantity'); ?></span>
		</td>
		<td class="center" colspan="2" style="padding:0.5em 0em;">
			×
		</td>
		<td class="center nobr">
			<span id="coupon_normal_price" class="coupon_price"><?=$coupon_price_sales?></span>円
		</td>
		<td class="center" colspan="2" style="padding:0.5em 0em;">
			＝
		</td>
		<td class="center nobr">
			<span id="price" class="coupon_price"><?=$coupon_price_total?></span>円
		</td>
	</tr>
	<tr>
		<td colspan="10" style="padding-left: 2em;" valign="top">
			<p class="small orange">▲数量の変更はこちらから</p>
		</td>
	</tr>
</table>

<div class="center">
	<?php $this->form()->Input( 'submit', $data->submit_label ); ?>
</div>
<?php $this->form()->Finish($data->form_name); ?>

<script>
//	ドキュメントが読み込まれたら実行
$(document).ready(function(){
	//  quantityが変更されたら価格を変更する。
	$('#quantity').change(function() {
		var price = $('#coupon_normal_price').text();
		var quantity = $('#quantity').val();
		
		price = price * quantity;
		
		$('#price').text(price);
	});
});
</script>