<?php
/* @var $this CouponApp */
$t_coupon = $data->t_coupon;
$quantity = $this->form()->GetValue('quantity',$data->form_name);
$quantity = ctype_digit($quantity) ? $quantity: 1;
$coupon_price_normal = $t_coupon['coupon_normal_price'];
$coupon_price_sales  = $t_coupon['coupon_sales_price'];
$coupon_price_total  = $quantity * $coupon_price_sales;
$coupon_description  = $t_coupon['coupon_description'];
?>

<?php $this->form()->Start( $data->form_name, $data->form_action ); ?>
<table style="border-collapse: collapse; width:100%;">
	<tr style="background-color: #DEEDCE;">
		<th style="border: 1px solid #CCCCCC; width:50%; height:">購入クーポン</th>
		<th>数量</th>
		<th>単価</th>
		<th>合計</th>
	</tr>
	<tr>
		<td>
			<img style="float:left; margin: 5px;" height="75px" src="../img/dummy.jpg">
			<p style="font-size:13px;"><?=$coupon_description?></p>
		</td>
		<td colspan="3" style="font-size: 40px; text-align:center;">
			<nobr>
				<span class="coupon_price">
					<span class="coupon_price"><?php $this->form()->Input('quantity'); ?></span>
					×
					<span id="coupon_normal_price" class="coupon_price"><?=$coupon_price_sales?></span>円
					＝
					<span id="price" class="coupon_price"><?=$coupon_price_total?></span>円
				</span>
			</nobr>
			<p style="font-size:13px; color: #FF9800;">▲数量の変更はこちらから</p>
		</td>
	</tr>
</table>
<div style="text-align:center">
	<?php $this->form()->Input( 'submit', $data->submit_label ); ?>
</div>
<?php $this->form()->Finish($data->form_name); ?>

<script>
//	ドキュメントが読み込まれたら実行
$(document).ready(function(){
	//  quantityが変更されたら価格を変更する。
	$('#quantity').change(function() {
		var price = $('#coupon_normal_price').text();
		var quantity = $('#quantity').val();
		
		price = price * quantity;
		
		$('#price').text(price);
	});
});
</script>