<?php
/* @var $this CouponApp */
?>
<div class="contents">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">クーポン購入</h1>
	</div>
	
	<h2 style="border-bottom: 4px solid #B0D485; margin-bottom: 10px; padding-top: 13px; font-size: 20px;">購入内容</h2>
	
	<div id="coupon_content" style="padding-top:8px;">
		<?php
		$data->form_name = $data->form_name_buy;
		$this->template('form_buy.phtml',$data);
		?>
	</div>
</div>
