<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="<?=$this->charset()?>">
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Style-Type" content="text/css">
	
	<meta name="keywords" content="<?=$this->Keywords()?>">
	<meta name="description" content="<?=$this->Description()?>">
	
	<link rel="stylesheet" type="text/css" href="/css/default.css">
	<link rel="stylesheet" type="text/css" href="/css/myshop.css">
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
	
	<!--  
	<script src="/js/jquery-1.8.3.js"></script>
	-->
	<script src="/js/jquery.ui.datetimepicker.js"></script>
	<script src="/js/jquery.ui.datetimepicker-jp.js"></script>
	
	<link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css" rel="stylesheet" />
	
	<!--[if IE]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	
	<title><?=$this->title()?></title>
</head>
<body id="myshop">
<div>
	[ 
	<a href="<?php print $this->ConvertUrl('/'); ?>">TOP</a> | 
	<a href="<?php print $this->ConvertUrl('/myshop'); ?>">MyShop</a>
	]
</div>
<section>
<?php $this->Content(); ?>
</section>
<div>
	Copyright (C) 2012 OnePiece Framework Projects.
</div>
</body>
</html>
