<div>
	<?php $this->form()->Start('form_shop','commit') ?>
		<table>
			<tr>
				<td>
					<?php $this->form()->Label('shop_name') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_name') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_description') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_description') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_pref') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_pref') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_city') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_city') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_address') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_address') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_building') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_building') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_tel') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_tel') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_holiday') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_holiday') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_open') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_open') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_close') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_close') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_railway') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_railway') ?>
				</td>
			</tr>
			<tr>
				<td>
					<?php $this->form()->Label('shop_station') ?>
				</td>
				<td>
					<?php $this->form()->Value('shop_station') ?>
				</td>
			</tr>
			<tr>
				<td>
				
				</td>
				<td>
					<?php $this->form()->Input('submit',' commit ') ?>
				</td>
			</tr>
		</table>
	<?php $this->form()->Finish('form_shop') ?>
</div>