<?php
/* @var $this CouponApp */
?>
<style>
	#customer_informartion p{
		font-size: 14px;
	}
	#customer_informartion th, td {
		border: 1px solid #CCCCCC;
	}
	#customer_informartion table tr{
		height:2px;
	}
	
	#customer_informartion table tr th{
		background: none repeat scroll 0 0 #DEEDCE;
		font-size: 14px;
		width: 20px;
		padding: 8px 0;
		padding-left: 8px;
		width:100px;
	}
	
	#customer_informartion table tr td{
		/*width:400px;*/
		padding: 20px 0;
		font-size: 14px; 
		padding-left: 10px;
	}
	
	.submit{
		background: -moz-linear-gradient(center top , #78BED8, #309FC4) repeat scroll 0 0 transparent;
		-webkit-box-shadow:rgba(0, 0, 0, 0.496094) 0 2px 4px;
		background-image:-webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8), to(#309FC4));
		border: 1px solid #2D9DC2;
		border-radius: 9px 9px 9px 9px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		margin: 15px;
		padding: 4px 30px;
		text-align: center;
		text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
		vertical-align: middle;
	}
</style>

<?php if( isset($data->message) ): ?>
	<p class="red"><?=$data->message?></p>
<?php endif; ?>

<?=$this->form()->Start('form_address','commit');?>

<div class="arc" style="border: 0px dotted red; background-color:white; margin:5px; padding:13px;">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">登録情報</h1>
	</div>
	
	<div id="customer_informartion" style="padding-top:8px;">	
		<h1 style="font-size: 16px;">お客様の基本情報</h1>
		
		<p>姓：<?php $this->form()->Value('last_name');?></p>
		<p>名：<?php $this->form()->Value('first_name');?></p>
		<p>郵便番号：<?php $this->form()->Value('zipcode');?></p>
		<p>都道府県：<?php $this->form()->Value('pref');?></p>
		<p>市区町村：<?php $this->form()->Value('city');?></p>
		<p>丁目番地：<?php $this->form()->Value('address');?></p>
		<p>建物名：<?php $this->form()->Value('building');?></p>
		<div style="text-align:center">
			<?php $this->form()->Input('submit','この内容で登録する')?>
		</div>		
	</div>
</div>
<?php $this->form()->Finish('form_address'); ?>