<?php
/* @var $this CouponApp */
?>
<style>
	.confirm{
		border: 0px dotted red; 
		background-color:white; 
		margin:5px; 
		padding:13px;
	}
	.title{
		font-size: 20px; 
		border-bottom: 1px solid #D9D9D9; 
		margin-top: 8px; 
		padding-bottom: 13px;
	}
	.title h1{
		font-size: 20px;
	}
	.contents2{
		padding-top:8px;
	}
	.contents2 p{
		font-size: 14px;
	}
	.contents2 th, td {
		border: 1px solid #CCCCCC;
	}
	.contents2 table{
		border-collapse: collapse;
	}
	.contents2 table tr{
		height:50px; 
		padding: 25px 0;
		text-align: left;
	}
	
	.contents2 table tr th{
		background: none repeat scroll 0 0 #DEEDCE;
		font-size: 14px;
		width: 20px;
		padding: 8px 0;
		padding-left: 8px;
		width:100px;
		/*width:5px;*/
	}
	
	.contents2 table tr td{
		width:400px;
		padding: 20px 0;
		font-size: 14px; 
		padding-left: 10px;
	}
	
	.div_submit{
		text-align:center;
	}
	.submit{
		background: -moz-linear-gradient(center top , #78BED8, #309FC4) repeat scroll 0 0 transparent;
		-webkit-box-shadow:rgba(0, 0, 0, 0.496094) 0 2px 4px;
		background-image:-webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8), to(#309FC4));
		border: 1px solid #2D9DC2;
		border-radius: 9px 9px 9px 9px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		margin: 15px;
		padding: 4px 30px;
		text-align: center;
		text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
		vertical-align: middle;
	}
</style>

<?=$this->form()->Start('form_customer','commit');?>

<div class="arc confirm">
	<div class="title">
		<h1>登録情報 - 確認</h1>
	</div>
	<div class="contents2">
		<table>
			<tr>
				<th>名前</th>
				<td>
					<span>
						姓：<?php $this->form()->Value('last_name');?>
						名：<?php $this->form()->Value('first_name');?>
					</span>
				</td>
			</tr>
			<?php
			/*
			<tr align="left">
				<th>都道府県</th>
				<td><?php $this->form()->Value('pref'); ?></td>
			</tr>
			<tr align="left">
				<th>市区町村</th>
				<td>
					<?php $this->form()->Value('city'); ?>
				</td>
			</tr>
			<tr align="left">
				<th>丁目番地</th>
				<td>
					<?php $this->form()->Value('address'); ?>
				</td>
			</tr>
			<tr align="left">
				<th>建物名</th>
				<td>
					<?php $this->form()->Value('building'); ?>
				</td>
			</tr>
			
			<tr align="left">
				<th>myエリア</th>
				<td>
					<?php $this->form()->Value('myarea'); ?>
				</td>
			</tr>
			
			*/
			?>
			<tr>
				<th>生年月日</th>
				<td>
					<?php $this->form()->Value('birthday') ?>
				</td>
			</tr>
			<tr>
				<th>性別</th>
				<td>
					<?php $this->form()->Value('gender'); ?>
				</td>
			</tr>
		</table>
		<div class="div_submit">
			<?php $this->form()->Input('submit')?>
		</div>
	</div>
</div>
<?php $this->form()->Finish('form_customer'); ?>