<?php
/* @var $this CouponApp */
?>
<style>
	#customer_informartion p{
		font-size: 14px;
	}
	#customer_informartion th, td {
		border: 1px solid #CCCCCC;
	}
	#customer_informartion table tr{
		height:2px;
	}
	
	#customer_informartion table tr th{
		background: none repeat scroll 0 0 #DEEDCE;
		font-size: 14px;
		width: 20px;
		padding: 8px 0;
		padding-left: 8px;
		width:100px;
	}
	
	#customer_informartion table tr td{
		/*width:400px;*/
		padding: 20px 0;
		font-size: 14px; 
		padding-left: 10px;
	}
	
	.submit{
		background: -moz-linear-gradient(center top , #78BED8, #309FC4) repeat scroll 0 0 transparent;
		-webkit-box-shadow:rgba(0, 0, 0, 0.496094) 0 2px 4px;
		background-image:-webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8), to(#309FC4));
		border: 1px solid #2D9DC2;
		border-radius: 9px 9px 9px 9px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		margin: 15px;
		padding: 4px 30px;
		text-align: center;
		text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
		vertical-align: middle;
	}
</style>

<?php if( isset($data->message) ): ?>
	<p class="red"><?=$data->message?></p>
<?php endif; ?>

<?=$this->form()->Start('form_customer','confirm');?>

<div class="arc" style="border: 0px dotted red; background-color:white; margin:5px; padding:13px;">
	<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 13px;">
		<h1 style="font-size: 20px;">登録情報</h1>
	</div>
	<div id="customer_informartion" style="padding-top:8px;">
		<table style="border-collapse: collapse;">
			<tr style="height:50px; padding: 25px 0;" align="left">
				<th style="width:5px;">名前</th>
				<td style="width:400px;">
					姓：<?php $this->form()->Input('last_name');?>
					名：<?php $this->form()->Input('first_name');?>
					<p class="red"><?php $this->form()->InputError('last_name')?></p>
					<p class="red"><?php $this->form()->InputError('first_name')?></p>
				</td>
			</tr>
			<?php
			/*
			<tr align="left">
				<th>郵便番号</th>
				<td>
					<?php $this->form()->Input('zipcode'); ?>
					<p class="red"><?php $this->form()->InputError('zipcode');?></p>
				</td>
			</tr>
			<tr align="left">
				<th>都道府県</th>
				<td>
					<?php $this->form()->Input('pref'); ?>
					<p class="red"><?php $this->form()->InputError('pref');?></p>
				</td>
			</tr>
			<tr align="left">
				<th>市区町村</th>
				<td>
					<?php $this->form()->Input('city'); ?>
					<p class="red"><?php $this->form()->InputError('city');?></p>
					<p>例：新宿区</p>
				</td>
			</tr>
			<tr align="left">
				<th>丁目番地</th>
				<td>
					<?php $this->form()->Input('address'); ?>
					<p class="red"><?php $this->form()->InputError('address');?></p>
					<p>例：新宿1-1-1</p>
				</td>
			</tr>
			<tr align="left">
				<th>建物名</th>
				<td>
					<?php $this->form()->Input('building'); ?>
					<p class="red"><?php $this->form()->InputError('building');?></p>
					<p>例：新宿ビル5F</p>
				</td>
			</tr>
			
			<tr align="left">
				<th>myエリア</th>
				<td>
					<?php $this->form()->Input('myarea'); ?>
					<p class="red"><?php $this->form()->InputError('myarea');?></p>
				</td>
			</tr>
			
			*/
			?>
			<tr align="left">
				<th>メールアドレス</th>
				<td>
					メールアドレスはt_account.emailに暗号化されて入っている
					<a href="/mypage/customer/mailaddr_change">変更する</a>
				</td>
			</tr>
			<tr align="left">
				<th>パスワード</th>
				<td><?php echo '******'; ?><a href="/mypage/customer/password_change">変更する</a></td>
			</tr>
			<tr align="left">
				<th>生年月日</th>
				<td>
					<?php $this->form()->Input('birthday') ?>
					<p class="red"><?php $this->form()->Error('birthday') ?></p>
				</td>
			</tr>
			<tr align="left">
				<th>性別</th>
				<td>
					<?php $this->form()->Input('gender'); ?>
					<p class="red"><?php $this->form()->InputError('gender');?></p>
				</td>
			</tr>
		</table>
		<div style="text-align:center">
			<?php $this->form()->Input('submit')?>
		</div>
	</div>
</div>
<?php $this->form()->Finish('form_customer'); ?>