<?php $this->mark(); ?>
<style>
	.message{
		margin-left:20px; 
		color: #999999; 
		font-size:14px; 
		font-weight: bold; 
		margin-bottom: 10px;
		border-bottom: 1px solid #D9D9D9;
	}
	.password_input{
		margin-bottom: 10px;
		margin-left: 40px;
	}
	.input_button{
		background: -moz-linear-gradient(center top , #78BED8, #309FC4) repeat scroll 0 0 transparent;
		-webkit-box-shadow:rgba(0, 0, 0, 0.496094) 0 2px 4px;
		background-image:-webkit-gradient(linear, 0 0%, 0 100%, from(#78BED8), to(#309FC4));
		border: 1px solid #2D9DC2;
		border-radius: 9px 9px 9px 9px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		margin: 15px;
		padding: 4px 30px;
		text-align: center;
		text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.5);
		vertical-align: middle;
	}
</style>

<?php $this->form->Start('password_change'); ?>

<div class="arc" style="border: 0px dotted red; background-color:white; margin:5px; padding:13px;">
	<div style="margin-left:30px;">
		<div class="hgroup1" style="font-size: 20px; border-bottom: 1px solid #D9D9D9; margin-top: 8px; padding-bottom: 10px;">
			<h1 style="font-size: 20px; ">パスワード変更</h1>
		</div>
		<div class="password_change" style="margin-top:10px;">
			<p class="red"><?=@$error?></p>
			<p class="message">現在のパスワードを入力してください。</p>
			<?php $this->form->Input('old_password');?>
			<p class="red"><?php $this->form->InputError('old_password');?></p>

			<p class="message">新しいパスワードを入力してください。</p>
			<?php $this->form->Input('new_password');?>
			<p class="red"><?php $this->form->InputError('new_password');?></p>
			
			<p class="message">新しいパスワードを入力してください。（確認用）</p>
			<?php $this->form->Input('new_password_confirm');?>
			<p class="red"><?php $this->form->InputError('new_password_confirm');?></p>
		</div>
	</div>
	
	<div style="text-align:center">
		<?=$this->form->Input('submit_button')?>
	</div>
</div>

<?php $this->form->Finish('password_change'); ?>

