<?php
/* @var $this CouponApp */
?>
<div>
	確認コードを以下のメールアドレスに送信します。	
</div>
<br>
<?php $this->form()->Start( $data->form_name, 'commit' ) ?>
	<?php $this->form()->Label('email') ?>
	<?php $this->form()->Value('email') ?><br>
	<?php $this->form()->Input('submit','　確認コードを送信する　') ?>
<?php $this->form()->Finish($data->form_name) ?>

<div>
	<form action="./">
		<input type="submit" value="送信先のメールアドレスを修正する" class="submit">
	</form>
</div>
