<?php $this->form()->Start($form_name, $this->ConvertURL("ctrl:/$coupon_id/commit")) ?>
<table>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_title') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_title') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_description') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_description') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_normal_price') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_normal_price') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_price') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_sales_price') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_num_top') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_sales_num_top') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_num_bottom') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_sales_num_bottom') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_start') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_sales_start') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_finish') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_sales_finish') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_expire') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_expire') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_person_num') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_person_num') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_hidden') ?>
		</td>
		<td>
			<?php $this->form()->Value('coupon_hidden') ?>
		</td>
	</tr>
	<tr>
		<td>
		
		</td>
		<td>
			<?php $this->form()->Input('submit',' Update ') ?>
		</td>
	</tr>
</table>
<?php $this->form()->Finish($form_name) ?>