<?php if( isset($message) ): ?>
	<p class="blue" style="margin: 1em; font-size: 125%;"><?=$message?></p>
<?php endif; ?>
<?php $this->form()->Start($form_name, $this->ConvertURL("ctrl:/$coupon_id/confirm")) ?>
<table>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_title') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_title') ?><br/>
			<?php $this->form()->Error('coupon_title') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_description') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_description') ?><br/>
			<?php $this->form()->Error('coupon_description') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_normal_price') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_normal_price') ?><br/>
			<?php $this->form()->Error('coupon_normal_price') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_price') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_sales_price') ?><br/>
			<?php $this->form()->Error('coupon_sales_price') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_num_top') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_sales_num_top') ?><br/>
			<?php $this->form()->Error('coupon_sales_num_top') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_num_bottom') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_sales_num_bottom') ?><br/>
			<?php $this->form()->Error('coupon_sales_num_bottom') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_start') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_sales_start') ?><br/>
			<?php $this->form()->Error('coupon_sales_start') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_sales_finish') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_sales_finish') ?><br/>
			<?php $this->form()->Error('coupon_sales_finish') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_expire') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_expire') ?><br/>
			<?php $this->form()->Error('coupon_expire') ?>
		</td>
	</tr>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_person_num') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_person_num') ?><br/>
			<?php $this->form()->Error('coupon_person_num') ?>
		</td>
	</tr>
	<?php
	/*
	<tr>
		<td>
			<?php $this->form()->Label('coupon_hidden') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_hidden') ?><br/>
			<?php $this->form()->Error('coupon_hidden') ?>
		</td>
	</tr>
	*/
	?>
	<tr>
		<td>
			<?php $this->form()->Label('coupon_image') ?>
		</td>
		<td>
			<?php $this->form()->Input('coupon_image') ?><br/>
			<?php $this->form()->Error('coupon_image') ?>
		</td>
	</tr>
	<tr>
		<td>
		
		</td>
		<td>
			<?php $this->form()->Input('submit',' confirm ') ?>
		</td>
	</tr>
</table>
<?php $this->form()->Finish($form_name) ?>
