<head>
	<meta charset="<?=$this->charset()?>">
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Style-Type" content="text/css">
	
	<meta name="keywords" content="<?=$this->Keywords()?>">
	<meta name="description" content="<?=$this->Description()?>">
	
	<link rel="stylesheet" type="text/css" href="/css/import.css">
	<link rel="stylesheet" type="text/css" href="/css/default.css">
	<link rel="stylesheet" type="text/css" href="/css/coupon.css">
	
	<script type="text/javascript" src="/jQueryUI/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/jQueryUI/js/jquery-ui-1.8.22.custom.min.js"></script>
	
	<title><?=$this->title()?></title>
</head>
