<head>
	<meta charset="<?=$this->GetCharset()?>">
	
	<meta http-equiv="Content-Type" content="text/html; charset=<?=$this->GetCharset()?>">
	<meta http-equiv="Content-Style-Type" content="text/css">
	
	<meta name="keywords" content="<?=$this->GetKeywords()?>">
	<meta name="description" content="<?=$this->GetDescription()?>">
	
	<link rel="stylesheet" type="text/css" href="/css/import.css">
	
	<script type="text/javascript" src="/jQueryUI/js/jquery.js"></script>
	<script type="text/javascript" src="/jQueryUI/js/jquery-ui.js"></script>
	
	<!-- load jQuery -->
    <?php if($this->admin()): ?>
        <script src="/js/jquery-1.7.1.js"></script>
    <?php else: ?>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <?php endif; ?>
    
    <!-- onlad after start user create main function of JavaScript. -->
    <script>
        $(function(){
            if(typeof window.main == 'function') {
                main();
            }
        })
    </script>
    
    <title><?=$this->GetTitle()?></title>
</head>
