<div style="border: 0px dotted red; background-color:white; margin:5px; padding:5px;" class="arc">
<table>
	<tr>
		<td colspan="2" valign="top">
			<h1><?=$t_coupon['coupon_title']?></h1>
		</td>
	</tr>
	<tr>
		<td valign="top">
			<?=$this->template('coupon_buy_form.phtml',array('t_coupon'=>$t_coupon))?>
		</td>
		<td valign="top">
			<?=$this->template('coupon_info_detail.phtml',array('t_coupon'=>$t_coupon))?>
			<p><?=$t_coupon['coupon_description']?></p>
			<p style="color:#8AB657; font-size:90%; border-bottom:2px solid #E3E3E3" class="bold">ご利用上の注意</p>
			<p>ここにご利用上の注意が必要</p>
		</td>
	</tr>
</table>
</div>

<div style="border: 0px dotted red; background-color:white; margin:5px; padding:5px;" class="arc">
	<p>ここがお店の説明欄</p>
	<?=$this->template('coupon_info_shop.phtml',array('t_shop'=>$t_shop))?>
</div>
