<div style="border: 1px solid black;">
	<div>
		<img src="/img/dummy.jpg" style="width:360px; height:240px; border:1px dotted gray;">
	</div>
	<div>
		<img src="/img/dummy.jpg" style="width:90px; height:80px; border:1px dotted gray;">
		<img src="/img/dummy.jpg" style="width:90px; height:80px; border:1px dotted gray;">
		<img src="/img/dummy.jpg" style="width:90px; height:80px; border:1px dotted gray;">
		<img src="/img/dummy.jpg" style="width:90px; height:80px; border:1px dotted gray;">
	</div>
</div>