<?php
/* @var $this CouponApp */

//  Get select config
$config = new Config();
$config->table = 't_coupon';
$config->limit = 10;
$config = $this->config()->select_coupon_list();
$t_coupon = $this->pdo()->select($config);

?>
<style>

#info_coupon_small{
	margin:3px;
	padding-bottom: 5px;
	background-color: #f0ffdd;
	border:1px solid gray;
	font-size: small;
	width: 234px;
}

#info_coupon_small div.info_coupon_small{
	padding: 3px;
	font-size: small;
	border:1px solid grey;
	border-width: 1px 0px 0px 0px;
}

#info_coupon_small p.info_coupon_small{
	font-size: small;
}

</style>
<div id="info_coupon_small" class="arc" >
	<div class="center" style="">
		<p class="small">おすすめのクーポン</p>
	</div>
	<?php foreach($t_coupon as $coupon): ?>
	<?php $this->Template('right_side_info_small.phtml',$coupon); ?>
	<?php endforeach; ?>
</div>

