<?php
/* @var $this CouponApp */
$action    = $data->form_action;
$coupon_id = $data->coupon_id;
$record    = $data->record;
$num       = $this->form()->GetValue('num','form_buy');
$num = $num ? $num: 1;
?>
<?php $this->form()->Start('form_buy',$action) ?>
<table>
	<tr>
		<td>購入クーポン</td>
		<td>数量</td>
		<td>単価</td>
		<td>合計</td>
	</tr>
	<tr>
		<td>
			
		</td>
		<td>
			<?php $this->form()->Input('num') ?>
		</td>
		<td>
			<?=number_format($record['coupon_sales_price'])?>
		</td>
		<td>
			<?=number_format($record['coupon_sales_price'] * $num)?>
		</td>
	</tr>
</table>
<div class="center">
	<?php $this->form()->Input('submit',$data->submit_label) ?>
</div>
<?php $this->form()->Finish('form_buy') ?>
