		<?php $this->form()->Start($data->form_name,$data->form_action);?>
		<table style="border-collapse:collapse;">
			<tr style="height:50px; padding: 25px 0;" align="left">
				<th style="width:5px;">名前</th>
				<td style="width:400px;">
					姓：<?php $this->form()->Value('last_name');?>
					名：<?php $this->form()->Value('first_name');?>
				</td>
			</tr>
			
			<tr align="left">
				<th>郵便番号</th>
				<td>
					<?php $this->form()->Value('zipcode'); ?>
				</td>
			</tr>
			
			<tr align="left">
				<th>都道府県</th>
				<td>
					<?php $this->form()->Value('pref'); ?>
				</td>
			</tr>
		
			<tr align="left">
				<th>市区町村</th>
				<td>
					<?php $this->form()->Value('city'); ?>
					<p>例：新宿区</p>
				</td>
			</tr>
		
			<tr align="left">
				<th>丁目番地</th>
				<td>
					<?php $this->form()->Value('address'); ?>
				</td>
			</tr>
		
			<tr align="left">
				<th>建物名</th>
				<td>
					<?php $this->form()->Value('building'); ?>
				</td>
			</tr>
		</table>
		<div style="text-align:center">
			<?php $this->form()->Input('submit',' この内容で登録する ')?>
		</div>
		<?php $this->form()->Finish($data->form_name); ?>